<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Txt-ValidForVal</name>
   <tag></tag>
   <elementGuidId>5d5af0c8-4c40-4948-9ed5-02207c1c9457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[normalize-space()='Valid For (Days)']/following-sibling::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>7dc64055-30a5-412a-bcba-1809867192b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1765253391799</value>
      <webElementGuid>5a2988f8-2034-4a8e-b5e6-58fad9d37ed3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
