<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Txt-PreparedForVal</name>
   <tag></tag>
   <elementGuidId>5b068b1c-97a1-42ce-ac5f-fe8ea5fdc2fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[normalize-space()='Prepared For']/following-sibling::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f8553cea-2067-4e82-a2c0-406e75e0195e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1765253015305</value>
      <webElementGuid>4bd0124f-79f4-41fa-9885-9be5c804f0d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
