<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Txt-PreparedByNameVal</name>
   <tag></tag>
   <elementGuidId>de3cb520-eb5e-4919-a396-ea0275e57035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[normalize-space()='Prepared By']/following-sibling::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>550b1c72-6626-4a0b-b525-725b36ec37b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1765253515977</value>
      <webElementGuid>059b358e-a9f5-45e8-99f8-e2399d076893</webElementGuid>
   </webElementProperties>
</WebElementEntity>
