<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Etc-LoadingAnimation</name>
   <tag></tag>
   <elementGuidId>ff84b6c8-0bf9-4ba0-ad6d-995710f37720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-loading']/dotlottie-wc</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>dotlottie-wc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>dotlottie-wc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dotlottie-wc</value>
      <webElementGuid>0f0d74b7-9c74-45da-8ecc-9aef3e71fedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/oneui-root-config/splashscreen.lottie</value>
      <webElementGuid>ece611b5-f289-4c38-9f23-ad39f547636f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>background</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>b9dc0c16-4cff-40f1-867c-e42a9e3d20d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>speed</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f0f7960a-9f25-4e8c-b54c-3a064527de4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-loading&quot;)/dotlottie-wc[1]</value>
      <webElementGuid>22ddf719-154e-49b2-bc88-c6f89863e44b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-loading']/dotlottie-wc</value>
      <webElementGuid>bb8541c7-673d-46d4-9d89-5efe5d1c061b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dotlottie-wc</value>
      <webElementGuid>6846d253-9d44-4911-9913-741b2e89b46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dotlottie-wc[@src = '/static/oneui-root-config/splashscreen.lottie']</value>
      <webElementGuid>0bba0579-41f3-45ee-bdac-203cf2541b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
